// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// import coffeeStores from '../data/coffee-stores.json';

// //accessing coffeeStore from dummy data/coffee-stores.json file
// export default function Home() {
//   // console.log('StylesHome', styles);
//   const handleOnBannerBtnClick = () => {
//     console.log('Hi banner button');
//   };
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText="View stores nearby"
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>
//         <div className={styles.cardLayout}>
//           {coffeeStores.map((coffeeStore) => {
//             return (
//               <Card
//                 key={coffeeStore.id}
//                 name={coffeeStore.name}
//                 imgUrl={coffeeStore.imgUrl}
//                 href={`/coffee-store/${coffeeStore.id}`}
//                 className={styles.card}
//               />
//             );
//           })}
//         </div>
//       </main>
//     </div>
//   );
// }

// //using getStaticProps function to fetch data from external api function
// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// import coffeeStores from '../data/coffee-stores.json';

// //getStaticProps() is a server side code
// export async function getStaticProps(context) {
//   console.log('Hi getStaticProps'); //print on the dev server in vscode
//   return {
//     props: {
//       coffeeStores, //pass this coffeeStores data onto component as props
//     },
//   };
// }

// //client side code
// export default function Home(props) {
//   // console.log('props: ', props); //props from getStaticProps() function

//   const handleOnBannerBtnClick = () => {
//     console.log('Hi banner button');
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText="View stores nearby"
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>

//         {props.coffeeStores.length > 0 && (
//           <div>
//             <h2 className={styles.heading2}>Toronto Stores</h2>
//             <div className={styles.cardLayout}>
//               {props.coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.id}
//                     name={coffeeStore.name}
//                     imgUrl={coffeeStore.imgUrl}
//                     href={`/coffee-store/${coffeeStore.id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}
//       </main>
//     </div>
//   );
// }

// //Using Foursquare Place Api in place of dummy json data
// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// // import coffeeStores from '../data/coffee-stores.json';

// //getStaticProps() is a server side code
// export async function getStaticProps(context) {
//   console.log('Hi getStaticProps'); //print on the dev server in vscode

//   //copy foursquare api from console onto getStaticProps method
//   // fetch(
//   //   'https://api.foursquare.com/v3/places/nearby?query=coffee&ll=6.523999122374296,3.3772545789333024',
//   //   {
//   //     headers: {
//   //       Authorization: 'fsq3fcQz2lk/7LskOPdFr+OCA50KH3HnOYQ3mUQlB7OI4RE=',
//   //       // Authorization: 'fsq3Kv9L0FtscscNu2491KgYhbS0DYyRPWJSOT7AzhtAz2k=', //hameedah
//   //     },
//   //   }
//   // )
//   //   .then((response) => response.json())
//   //   .then((data) => console.log(data));

//   // return {
//   //   props: {
//   //     coffeeStores: data.results, //pass this coffeeStores data onto component as props
//   //   },
//   // };

//     //Convert fetch()api to Async Await inorder to access the response easily
//     const response = await fetch(
//       'https://api.foursquare.com/v3/places/nearby?query=coffee stores&ll=6.523999122374296,3.3772545789333024&limit=6',
//       {
//         headers: {
//           // Authorization: 'fsq3fcQz2lk/7LskOPdFr+OCA50KH3HnOYQ3mUQlB7OI4RE=',
//           Authorization: 'fsq3Kv9L0FtscscNu2491KgYhbS0DYyRPWJSOT7AzhtAz2k=', //hameedah
//         },
//       }
//     );
//     const data = await response.json();
//     console.log('dataFSQ: ', data.results);

//     return {
//       props: {
//         coffeeStores: data.results, //pass this coffeeStores data onto component as props
//       },
//     };
//   }

//   return {
//     props: {
//       coffeeStores, //pass this coffeeStores data onto component as props
//     },
//   };
// }

// //client side code
// export default function Home(props) {
//   const handleOnBannerBtnClick = () => {
//     console.log('Hi banner button');
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText="View stores nearby"
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>

//         {props.coffeeStores.length > 0 && (
//           <div>
//             <h2 className={styles.heading2}>Toronto Stores</h2>
//             <div className={styles.cardLayout}>
//               {props.coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}
//       </main>
//     </div>
//   );
// }

// //cut fetch api of Foursquare places api to lib/coffee-stores.js file for reusable purpose
// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// import { fetchCoffeeStores } from './lib/coffee-stores';
// import UserTrackLocation from '../hooks/user-track-location';
// import { useEffect, useState } from 'react';

// //getStaticProps() is a server side code
// export async function getStaticProps(context) {
//   console.log('Hi getStaticProps'); //print on the dev server in vscode

//   const coffeeStores = await fetchCoffeeStores(); //fetchCoffeeStores() is using initial argument which are latLong and limit
//   console.log('indexCoffeeStores: ', coffeeStores);

//   return {
//     props: {
//       coffeeStores, //pass this coffeeStores data onto component as props
//     },
//   };
// }

// //client side code
// export default function Home(props) {
//   const [coffeeStores, setCoffeeStores] = useState('');

//   const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } =
//     UserTrackLocation();

//   console.log('latLong', latLong, 'locationErrorMsg', locationErrorMsg);

//   useEffect(() => {
//     const fetchData = async () => {
//       if (latLong) {
//         try {
//           const fetchedCoffee = await fetchCoffeeStores(latLong, 30);
//           console.log('fetchedCoffee: ', fetchedCoffee);
//           setCoffeeStores(fetchedCoffee);
//         } catch (err) {
//           console.log(err);
//         }
//       }
//     };
//     fetchData();
//   }, [latLong]);

//   const handleOnBannerBtnClick = () => {
//     // console.log('Hi banner button');
//     handleTrackLocation(); //its return latitude and longitude
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText={isFindingLocation ? 'Locating...' : 'View stores nearby'}
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         {locationErrorMsg && <p>Something went wrong:{locationErrorMsg}</p>}

//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>

//         {/*Lagos Coffee Stores*/}
//         {props.coffeeStores.length > 0 && (
//           <div className={styles.sectionWrapper}>
//             <h2 className={styles.heading2}>Lagos Coffee Stores</h2>
//             <div className={styles.cardLayout}>
//               {props.coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}
//       </main>
//     </div>
//   );
// }

// //Render the coffee stores fetch by clicking on View stores nearby button
// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// import { fetchCoffeeStores } from './lib/coffee-stores';
// import UserTrackLocation from '../hooks/user-track-location';
// import { useEffect, useState } from 'react';

// //getStaticProps() is a server side code
// export async function getStaticProps(context) {
//   console.log('Hi getStaticProps'); //print on the dev server in vscode

//   const coffeeStores = await fetchCoffeeStores(); //fetchCoffeeStores() is using initial argument which are latLong and limit
//   console.log('indexCoffeeStores: ', coffeeStores);

//   return {
//     props: {
//       coffeeStores, //pass this coffeeStores data onto component as props
//     },
//   };
// }

// //client side code
// export default function Home(props) {
//   const [coffeeStores, setCoffeeStores] = useState('');
//   const [coffeeStoresError, setCoffeeStoresError] = useState(null);

//   const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } =
//     UserTrackLocation();
//   console.log('latLong', latLong, 'locationErrorMsg', locationErrorMsg);

//   useEffect(() => {
//     const fetchData = async () => {
//       if (latLong) {
//         try {
//           const fetchedCoffee = await fetchCoffeeStores(latLong, 30);
//           console.log('fetchedCoffee: ', fetchedCoffee);
//           setCoffeeStores(fetchedCoffee);
//         } catch (err) {
//           console.log(err);
//           setCoffeeStoresError(err.message);
//         }
//       }
//     };
//     fetchData();
//   }, [latLong]);

//   const handleOnBannerBtnClick = () => {
//     // console.log('Hi banner button');
//     handleTrackLocation(); //its return latitude and longitude
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText={isFindingLocation ? 'Locating...' : 'View stores nearby'}
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         {locationErrorMsg && <p>Something went wrong:{locationErrorMsg}</p>}
//         {coffeeStoresError && <p>Something went wrong:{coffeeStoresError}</p>}

//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>

//         {/*Stores near me*/}
//         {coffeeStores.length > 0 && (
//           <div className={styles.sectionWrapper}>
//             <h2 className={styles.heading2}>Coffee stores near me</h2>
//             <div className={styles.cardLayout}>
//               {coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}

//         {/*Lagos Coffee Stores*/}
//         {props.coffeeStores.length > 0 && (
//           <div className={styles.sectionWrapper}>
//             <h2 className={styles.heading2}>Lagos Coffee Stores</h2>
//             <div className={styles.cardLayout}>
//               {props.coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}
//       </main>
//     </div>
//   );
// }

// //Using Context Store in getting fetchCoffeeStores() in place of local useState()
// import Head from 'next/head';
// import Image from 'next/image';
// import Banner from '../components/banner';
// import Card from '../components/card';
// import styles from '../styles/Home.module.css';
// import { fetchCoffeeStores } from './lib/coffee-stores';
// import UserTrackLocation from '../hooks/user-track-location';
// import { useEffect, useState, useContext } from 'react';
// import { ACTION_TYPES, StoreContext } from '../store/store-context';

// //getStaticProps() is a server side code
// export async function getStaticProps(context) {
//   console.log('Hi getStaticProps'); //print on the dev server in vscode

//   const coffeeStores = await fetchCoffeeStores(); //fetchCoffeeStores() is using initial argument which are latLong and limit
//   // console.log('indexCoffeeStores: ', coffeeStores);

//   return {
//     props: {
//       coffeeStores, //pass this coffeeStores data onto component as props
//     },
//   };
// }

// //client side code
// export default function Home(props) {
//   // const [coffeeStores, setCoffeeStores] = useState('');
//   const [coffeeStoresError, setCoffeeStoresError] = useState(null);
//   const { dispatch, state } = useContext(StoreContext); //fetching dispatch method from context store
//   const { coffeeStores, latLong } = state; //fetching coffeeStores data and latLong from context store

//   const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
//     UserTrackLocation();
//   // console.log('latLong', latLong, 'locationErrorMsg', locationErrorMsg);

//   useEffect(() => {
//     const fetchData = async () => {
//       if (latLong) {
//         try {
//           const fetchedCoffees = await fetchCoffeeStores(latLong, 30);
//           // console.log('fetchedCoffees: ', fetchedCoffees);
//           // setCoffeeStores(fetchedCoffees);
//           dispatch({
//             //dispatch fetchedCoffees to context store
//             type: ACTION_TYPES.SET_COFFEE_STORES,
//             payload: { coffeeStores: fetchedCoffees },
//           });
//         } catch (err) {
//           console.log(err);
//           setCoffeeStoresError(err.message);
//         }
//       }
//     };
//     fetchData();
//   }, [dispatch, latLong]);

//   const handleOnBannerBtnClick = () => {
//     // console.log('Hi banner button');
//     handleTrackLocation(); //its return latitude and longitude
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Coffee Connoisseur</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <Banner
//           buttonText={isFindingLocation ? 'Locating...' : 'View stores nearby'}
//           handleOnClick={handleOnBannerBtnClick}
//         />
//         {locationErrorMsg && <p>Something went wrong:{locationErrorMsg}</p>}
//         {coffeeStoresError && <p>Something went wrong:{coffeeStoresError}</p>}

//         <div className={styles.coffeeImage}>
//           <Image
//             src="/static/Coffee-Beans.png"
//             alt=""
//             width={700}
//             height={400}
//           />
//         </div>

//         {/*Stores near me*/}
//         {coffeeStores.length > 0 && (
//           <div className={styles.sectionWrapper}>
//             <h2 className={styles.heading2}>Coffee stores near me</h2>
//             <div className={styles.cardLayout}>
//               {coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}

//         {/*Lagos Coffee Stores*/}
//         {props.coffeeStores.length > 0 && (
//           <div className={styles.sectionWrapper}>
//             <h2 className={styles.heading2}>Lagos Coffee Stores</h2>
//             <div className={styles.cardLayout}>
//               {props.coffeeStores.map((coffeeStore) => {
//                 return (
//                   <Card
//                     key={coffeeStore.fsq_id}
//                     name={coffeeStore.name}
//                     imgUrl={
//                       coffeeStore.imgUrl ||
//                       'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
//                     }
//                     href={`/coffee-store/${coffeeStore.fsq_id}`}
//                     className={styles.card}
//                   />
//                 );
//               })}
//             </div>
//           </div>
//         )}
//       </main>
//     </div>
//   );
// }

//using serverless function api getCoffeeStoresByLocation in place of fetchCoffeeStores(latLong, 30)
//Using Context Store in getting fetchCoffeeStores() in place of local useState()
import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import Card from '../components/card';
import styles from '../styles/Home.module.css';
import FetchCoffeeStores from './lib/coffee-stores';
import UserTrackLocation from '../hooks/user-track-location';
import { useEffect, useState, useContext } from 'react';
import { ACTION_TYPES, StoreContext } from '../store/store-context';

//getStaticProps() is a server side code
export async function getStaticProps(context) {
  // console.log('Hi getStaticProps'); //print on the dev server in vscode

  const coffeeStores = await FetchCoffeeStores(); //fetchCoffeeStores() is using initial argument which are latLong and limit
  // console.log('indexCoffeeStores: ', coffeeStores);

  return {
    props: {
      coffeeStores, //pass this coffeeStores data onto component as props
    },
  };
}

//client side code
export default function Home(props) {
  // const [coffeeStores, setCoffeeStores] = useState('');
  const [coffeeStoresError, setCoffeeStoresError] = useState(null);
  const { dispatch, state } = useContext(StoreContext);
  const { coffeeStores, latLong } = state;

  const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
    UserTrackLocation();

  useEffect(() => {
    const fetchData = async () => {
      if (latLong) {
        try {
          // const fetchedCoffees = await fetchCoffeeStores(latLong, 30);
          const fetchedCoffees = await fetch(
            `/api/getCoffeeStoresByLocation?latLong=${latLong}&limit=30`
          );
          const coffeeStores = await fetchedCoffees.json();
          // console.log('fetchedCoffees:', coffeeStores);
          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: { coffeeStores },
          });
          setCoffeeStoresError('');
        } catch (err) {
          console.log(err);
          setCoffeeStoresError(err.message);
        }
      }
    };
    fetchData();
  }, [dispatch, latLong]);

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? 'Locating...' : 'View stores nearby'}
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMsg && <p>Something went wrong:{locationErrorMsg}</p>}
        {coffeeStoresError && <p>Something went wrong:{coffeeStoresError}</p>}

        <div className={styles.coffeeImage}>
          <Image
            src="/static/Coffee-Beans.png"
            alt=""
            width={700}
            height={400}
          />
        </div>

        {/*Stores near me*/}
        {coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Coffee stores near me</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}

        {/*Lagos Coffee Stores*/}
        {props.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Lagos Coffee Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'
                    }
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
